version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: queuequicker
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8800:8800"
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 900
  
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend